project:
  type: website
  render:
    - index.qmd
    - exploration.qmd
    - story.qmd
    - about.qmd
    - mongolia.qmd

website:
  title: "Weather Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Dashboard
      - href: exploration.qmd
        text: Exploration
      - href: story.qmd
        text: Story
      - href: mongolia.qmd
        text: Mongolia
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/angeladavdrj/sarasota-mongolia
        aria-label: GitHub
  page-footer:
    center: "Weather Dashboard | Created for Bayesian Data Science"

format:
  html:
    theme: flatly
    toc: true
    include-after-body: stickers.html

execute:
  echo: false
  warning: false
