project:
  type: website

website:
  title: "Weather Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Dashboard
      - href: exploration.qmd
        text: Exploration
      - href: story.qmd
        text: Story
    right:
      - icon: github
        href: https://github.com/angeladavdrj/sarasota-mongolia
        aria-label: GitHub
  page-footer:
    center: "Weather Dashboard | Created for Bayesian Data Science"

format:
  html:
    theme: flatly
    toc: true
    include-after-body: stickers.html

execute:
  echo: false
  warning: false
